server:
  port: 9000

spring:
  application:
    name: spring-cloud-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/seltonGitHub/cloudconfig.git
          password: 89l{:y3N{&ZS&s50ilXL[lz_i?LjgB
          username: seltonzyf@outlook.com


eureka:
  client:
    service-url: {"defaultZone": "http://localhost:8000/eureka/"}