
server:
  port: 8300

spring:
  application:
    name: spring-cloud-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/JZC-String/configserver.git
          password: Jzc...321
          username: JZC-String

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url: {"defaultZone": "http://localhost:8000/eureka/"}




