
server:
  port: 8300

spring:
  application:
    name: spring-cloud-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/seltonGitHub/cloudconfig.git
          password: 89l{:y3N{&ZS&s50ilXL[lz_i?LjgB
          username: seltonzyf@outlook.com
eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url: {"defaultZone": "http://localhost:8000/eureka/"}




